file_format: "1"
id: cygnus
name: The cygnus 
type: shield
url: https://github.com/stefanwatt/zmk-dongle
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - cygnus_left
  - cygnus_right
